"""Generate scorbot_controller.kicad_sch from design.py.

Every pin gets a short wire stub and a net label (or a no-connect flag), so
connectivity comes entirely from labels: easy to read, easy to regenerate.
"""
import copy
import os
import uuid

from kiutils.items.common import Effects, Font, Justify, PageSettings, Position, Property, Stroke, TitleBlock
from kiutils.items.schitems import (Connection, HierarchicalSheetInstance, LocalLabel, NoConnect,
                                    SchematicSymbol, SymbolProjectInstance, SymbolProjectPath, Text)
from kiutils.schematic import Schematic
from kiutils.symbol import SymbolLib

import design as D

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.normpath(os.path.join(HERE, ".."))
PROJECT_NAME = "scorbot_controller"
STD = "/usr/share/kicad/symbols/"
GRID = 1.27
CHAR_W = 1.1  # mm per label character (estimate)

_libs = {}


NS = uuid.UUID("5c0b0a7e-4e5d-4c6a-9f00-5c0b0a7e4e5d")
_count = [0]


def uid():
    """Deterministic UUIDs so regenerating gives a stable diff."""
    _count[0] += 1
    return str(uuid.uuid5(NS, f"item:{_count[0]}"))


def symbol_uuid(ref, unit):
    return str(uuid.uuid5(NS, f"sym:{ref}:{unit}"))


ROOT_UUID = str(uuid.uuid5(NS, "root"))


def snap(v, g=GRID):
    return round(round(v / g) * g, 4)


def load_symbol(lib_id):
    nick, name = lib_id.split(":")
    path = os.path.join(PROJ, "lib", "Scorbot.kicad_sym") if nick == "Scorbot" else STD + nick + ".kicad_sym"
    if path not in _libs:
        _libs[path] = {s.entryName: s for s in SymbolLib.from_file(path).symbols}
    by = _libs[path]
    s = by[name]
    if s.extends:  # flatten derived symbols for embedding
        parent = copy.deepcopy(by[s.extends])
        parent.entryName = s.entryName
        parent.properties = copy.deepcopy(s.properties)
        parent.extends = None
        for unit in parent.units:
            unit.entryName = s.entryName
        s = parent
    else:
        s = copy.deepcopy(s)
    s.libraryNickname = nick
    return s


def unit_pins(sym, unit):
    pins = []
    for un in sym.units:
        if un.unitId in (0, unit):
            pins.extend(un.pins)
    return pins


def unit_ids(sym):
    ids = sorted({un.unitId for un in sym.units if un.pins and un.unitId != 0})
    return ids or [1]


def pin_dir(angle):
    """Outward direction (dx, dy) in schematic coordinates (Y down)."""
    return {0: (-1, 0), 90: (0, 1), 180: (1, 0), 270: (0, -1)}[int(angle) % 360]


def font(size=1.27):
    return Font(height=size, width=size)


def lib_prop(sym, key):
    for pr in sym.properties:
        if pr.key == key:
            return pr
    return None


def text_box(x, y, angle, txt, justify=None):
    """Rough bounding box of a text item (schematic coords)."""
    w, h = len(txt) * CHAR_W, 1.6
    if int(angle) % 180 == 90:
        w, h = h, w
        return [x - w / 2, x + w / 2], [y - h / 2, y + h / 2]
    if justify == "left":
        return [x, x + w], [y - h, y + 0.4]
    if justify == "right":
        return [x - w, x], [y - h, y + 0.4]
    return [x - w / 2, x + w / 2], [y - h / 2, y + h / 2]


def sym_extent(sym, unit, nets, ref="", value=""):
    """Bounding box (schematic coords relative to origin) including labels and ref/value text."""
    xs, ys = [], []
    for key, txt in (("Reference", ref), ("Value", value)):
        pr = lib_prop(sym, key)
        if pr is None or not txt or (pr.effects and pr.effects.hide):
            continue
        j = pr.effects.justify.horizontally if pr.effects and pr.effects.justify else None
        bx, by = text_box(pr.position.X, -pr.position.Y, pr.position.angle or 0, txt, j)
        xs += bx
        ys += by
    for p in unit_pins(sym, unit):
        px, py = p.position.X, -p.position.Y
        dx, dy = pin_dir(p.position.angle)
        net = nets.get(str(p.number))
        lab = 2.54 + (len(net) * CHAR_W + 1.5 if net else 1.0)
        xs += [px, px + dx * lab]
        ys += [py, py + dy * lab]
        # body side of the pin
        xs.append(px - dx * p.length)
        ys.append(py - dy * p.length)
    if not xs:
        xs, ys = [-2, 2], [-2, 2]
    return min(xs) - 2, min(ys) - 4, max(xs) + 2, max(ys) + 4


class Sheet:
    def __init__(self):
        self.sch = Schematic.create_new()
        self.sch.version = "20230121"
        self.sch.generator = "eeschema"
        self.sch.uuid = ROOT_UUID
        self.sch.paper = PageSettings(paperSize="A1")
        self.sch.titleBlock = TitleBlock(title="Scorbot ER-4u ESP32 master board", date="2026-10-09",
                                         revision="0.1 (generated)", company="",
                                         comments={1: "Generated by generator/gen_schematic.py from design.py",
                                                   2: "Pololu carrier pin ORDER is a placeholder - see README"})
        self.embedded = {}

    def embed(self, lib_id):
        if lib_id not in self.embedded:
            s = load_symbol(lib_id)
            self.embedded[lib_id] = s
            self.sch.libSymbols.append(s)
        return self.embedded[lib_id]

    def text(self, txt, x, y, size=2.5):
        self.sch.texts.append(Text(text=txt.replace("\n", "\\n"), position=Position(x, y, 0),
                                   effects=Effects(font=Font(height=size, width=size, bold=True),
                                                   justify=Justify(horizontally="left")),
                                   uuid=uid()))

    def place(self, p, unit, x, y):
        sym = self.embedded[p["lib"]]
        nick, name = p["lib"].split(":")
        props = []
        ext = sym_extent(sym, unit, p["nets"], p["ref"], p["value"])
        is_pwr = p["ref"].startswith("#")
        ref_txt = p["ref"]
        values = [("Reference", ref_txt, is_pwr), ("Value", p["value"], is_pwr),
                  ("Footprint", p["fp"], True), ("Datasheet", "", True)]
        for k, (key, val, hide) in enumerate(values):
            lp = lib_prop(sym, key)
            if lp is not None:
                pos = Position(snap(x + lp.position.X, 0.01), snap(y - lp.position.Y, 0.01), lp.position.angle or 0)
                eff = copy.deepcopy(lp.effects) if lp.effects else Effects(font=font())
            else:
                pos, eff = Position(x, y, 0), Effects(font=font())
            eff.hide = hide or (lp is not None and lp.effects is not None and lp.effects.hide and key not in ("Reference", "Value"))
            props.append(Property(key=key, value=val, id=k, position=pos, effects=eff))
        pins = {}
        for pin in unit_pins(sym, unit):
            pins[str(pin.number)] = uid()
        s = SchematicSymbol(libraryNickname=nick, entryName=name, position=Position(x, y, 0), unit=unit,
                            inBom=not is_pwr and not p["ref"].startswith("H"), onBoard=not is_pwr,
                            dnp=p.get("dnp", False), uuid=symbol_uuid(p["ref"], unit), properties=props, pins=pins)
        s.instances = [SymbolProjectInstance(name=PROJECT_NAME, paths=[
            SymbolProjectPath(sheetInstancePath="/" + self.sch.uuid, reference=p["ref"], unit=unit)])]
        self.sch.schematicSymbols.append(s)
        p.setdefault("uuids", {})[unit] = s.uuid
        # stubs + labels
        for pin in unit_pins(sym, unit):
            num = str(pin.number)
            if num not in p["nets"]:
                print(f"warning: {p['ref']} pin {num} ({pin.name}) not in design; marked no-connect")
            net = p["nets"].get(num)
            px, py = snap(x + pin.position.X), snap(y - pin.position.Y)
            if net is None:
                self.sch.noConnects.append(NoConnect(position=Position(px, py), uuid=uid()))
                continue
            dx, dy = pin_dir(pin.position.angle)
            ex, ey = snap(px + dx * 2.54), snap(py + dy * 2.54)
            self.sch.graphicalItems.append(Connection(type="wire", points=[Position(px, py), Position(ex, ey)],
                                                    stroke=Stroke(width=0, type="default"), uuid=uid()))
            ang, just = {(-1, 0): (180, "right"), (1, 0): (0, "left"),
                         (0, -1): (90, "left"), (0, 1): (270, "right")}[(dx, dy)]
            self.sch.labels.append(LocalLabel(text=net, position=Position(ex, ey, ang),
                                              effects=Effects(font=font(), justify=Justify(horizontally=just, vertically="bottom")),
                                              uuid=uid()))

    def save(self, path):
        self.sch.sheetInstances = [HierarchicalSheetInstance(instancePath="/", page="1")]
        self.sch.to_file(path)


# Group order and the max row width (mm) each group may use. Groups are then
# shelf-packed onto the page in this order.
GROUPS = [
    ("power", 200, "POWER IN, REVERSE PROTECTION, E-STOP (no relay: NC contacts in VM line)"),
    ("buck", 150, "5 V: Pololu D24V22F5 plug-in buck + DEVKIT 5V FEED"),
    ("mcu", 120, "ESP32-DevKitC-32E (plug-in, 2x 1x19 female headers)"),
    ("i2c", 200, "I2C: TCA9555 (0x20) + 2x ADS1115 modules (0x48, 0x49)"),
    ("drivers", 330, "MOTOR DRIVERS: 6x Pololu DRV8874 carrier (plug-in) - PIN ORDER PLACEHOLDER"),
    ("encoders", 330, "ENCODER FRONT END: 47R VLED from 5V, 4.7k pull-ups to 3.3V, 1nF, direct to ESP32"),
    ("switches", 130, "HOME SWITCHES (to TCA9555 P1.0-P1.4)"),
    ("db50", 90, "ROBOT CABLE: DD-50 female (SCORBOT-ER 4u manual ch. 8)"),
    ("flags", 60, "POWER FLAGS"),
    ("holes", 40, "MOUNTING"),
]
PAGE_W, PAGE_H = 841, 594  # A1
MARGIN = 15


def layout_group(sh, g, max_w):
    """Return [(part, unit, dx, dy)], width, height for one group."""
    items, cx, cy, row_h, used_w = [], 0, 0, 0, 0
    for p in [q for q in D.PARTS if q["group"] == g]:
        sym = sh.embedded[p["lib"]]
        for unit in unit_ids(sym):
            ext = sym_extent(sym, unit, p["nets"], p["ref"], p["value"])
            w, h = ext[2] - ext[0], ext[3] - ext[1]
            if cx + w > max_w and cx > 0:
                cx, cy, row_h = 0, cy + row_h + 3, 0
            items.append((p, unit, cx - ext[0], cy - ext[1]))
            cx += w + 3
            used_w = max(used_w, cx)
            row_h = max(row_h, h)
    return items, used_w, cy + row_h


def build():
    sh = Sheet()
    for p in D.PARTS:
        sh.embed(p["lib"])
    x, y, shelf_h = MARGIN, MARGIN + 10, 0
    for g, max_w, title in GROUPS:
        items, w, h = layout_group(sh, g, max_w)
        if x + w > PAGE_W - MARGIN and x > MARGIN:
            x, y, shelf_h = MARGIN, y + shelf_h + 14, 0
        sh.text(title, x, y - 5, size=1.8)
        for p, unit, dx, dy in items:
            sh.place(p, unit, snap(x + dx, 2.54), snap(y + dy, 2.54))
        x += w + 12
        shelf_h = max(shelf_h, h)
    notes_y = y + shelf_h + 12
    if notes_y > PAGE_H - 45:
        print(f"warning: notes at y={notes_y:.0f} mm collide with the title block")
    sh.text("NOTES\n1. Pololu DRV8874 carrier pin ORDER is a placeholder (names are correct). Fix design.CARRIER_ROWS and regenerate.\n"
            "2. DB50 pinout from SCORBOT-ER 4u User Manual ch. 8 (same as ER III Table D-1). Pins 37-44 unused, 22 = gripper switch (no connection in arm).\n"
            "3. Plug-in module pin orders (Pololu D24V22F5, ADS1115 breakout) are placeholders: check against your modules.\n"
            "4. Carrier current limit with SLEEP at 3.3 V is about 2.9 A (VREF pulled to SLEEP by 10k on the carrier, CS has 2.49k). R21-R26 (DNP) lower it.\n"
            "5. Current sense: CS reads 1.12 V/A into ADS1115 modules (use the +/-4.096 V range). VM monitored via 47k/10k on ADS1115 #2 A2.",
            MARGIN, notes_y, size=1.8)
    path = os.path.join(PROJ, PROJECT_NAME + ".kicad_sch")
    sh.save(path)
    return path


if __name__ == "__main__":
    print("wrote", build())
